import { StyleSheet } from "react-native";

import { colors, spacing } from "./theme";

const panelShadow = {
  shadowColor: colors.shadow,
  shadowOffset: { width: 0, height: 12 },
  shadowOpacity: 0.08,
  shadowRadius: 26,
  elevation: 3,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  app: {
    flex: 1,
  },
  header: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    borderRadius: 24,
    backgroundColor: colors.ink,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.16,
    shadowRadius: 28,
    elevation: 5,
  },
  headerCopy: {
    flex: 1,
    paddingRight: spacing.md,
  },
  eyebrow: {
    alignSelf: "flex-start",
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: colors.lime,
    color: colors.limeInk,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  title: {
    marginTop: spacing.sm,
    color: colors.onInk,
    fontSize: 25,
    fontWeight: "900",
  },
  clearButton: {
    minHeight: 42,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.inkSoft,
    backgroundColor: colors.inkSoft,
    justifyContent: "center",
  },
  clearButtonText: {
    color: colors.onInk,
    fontWeight: "900",
  },
  content: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    gap: spacing.md,
  },
  panel: {
    padding: spacing.lg,
    borderRadius: 22,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.line,
    ...panelShadow,
  },
  panelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: spacing.md,
  },
  topicRow: {
    flexDirection: "row",
    gap: spacing.sm,
    paddingBottom: 2,
  },
  topicChip: {
    maxWidth: 240,
    minHeight: 46,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    justifyContent: "center",
    backgroundColor: colors.surfaceRaised,
  },
  topicChipActive: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  topicChipText: {
    color: colors.muted,
    fontWeight: "800",
  },
  topicChipTextActive: {
    color: colors.onInk,
  },
  segmented: {
    marginTop: spacing.md,
    padding: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: "row",
    backgroundColor: colors.surfaceMuted,
  },
  segment: {
    flex: 1,
    minHeight: 42,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 999,
  },
  segmentActive: {
    backgroundColor: colors.ink,
  },
  segmentText: {
    color: colors.muted,
    fontWeight: "900",
  },
  segmentTextActive: {
    color: colors.onInk,
  },
  personaRow: {
    gap: spacing.sm,
  },
  personaCard: {
    minHeight: 118,
    padding: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceRaised,
    justifyContent: "center",
  },
  personaCardActive: {
    borderColor: colors.lavenderStrong,
    backgroundColor: colors.lavender,
  },
  personaHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  personaName: {
    color: colors.ink,
    fontWeight: "900",
  },
  personaNameActive: {
    color: colors.lavenderInk,
  },
  personaGender: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  personaGenderActive: {
    color: colors.lavenderInk,
  },
  personaLabel: {
    marginTop: spacing.xs,
    color: colors.ink,
    fontWeight: "800",
  },
  personaLabelActive: {
    color: colors.lavenderInk,
  },
  personaDescription: {
    marginTop: spacing.xs,
    color: colors.muted,
    lineHeight: 20,
  },
  personaDescriptionActive: {
    color: colors.ink,
  },
  stanceLine: {
    marginTop: spacing.sm,
    padding: spacing.sm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceRaised,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  stanceLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  stanceValue: {
    flexShrink: 1,
    color: colors.ink,
    fontWeight: "900",
    textTransform: "capitalize",
    textAlign: "right",
  },
  stage: {
    minHeight: 260,
    padding: spacing.lg,
    borderRadius: 26,
    backgroundColor: colors.ink,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.lg,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 32,
    elevation: 6,
  },
  stageStatus: {
    minHeight: 24,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: colors.inkSoft,
    color: colors.onInk,
    fontWeight: "900",
    textAlign: "center",
  },
  wave: {
    width: "100%",
    minHeight: 92,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.inkSoft,
    backgroundColor: colors.inkSoft,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  waveActive: {
    borderColor: colors.lime,
    backgroundColor: colors.green,
  },
  waveBar: {
    width: 12,
    height: 34,
    borderRadius: 12,
    backgroundColor: colors.lavender,
  },
  waveBarTall: {
    height: 58,
    backgroundColor: colors.lime,
  },
  recordButton: {
    width: 132,
    height: 132,
    borderRadius: 66,
    backgroundColor: colors.lime,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 8,
    borderColor: colors.inkSoft,
  },
  recordButtonActive: {
    backgroundColor: colors.coral,
  },
  recordButtonDisabled: {
    opacity: 0.7,
  },
  recordButtonText: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  textInput: {
    minHeight: 92,
    padding: spacing.md,
    color: colors.ink,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    textAlignVertical: "top",
    backgroundColor: colors.surfaceRaised,
    lineHeight: 21,
  },
  titleInput: {
    minHeight: 46,
    marginBottom: spacing.sm,
    textAlignVertical: "center",
  },
  sourceInput: {
    minHeight: 150,
  },
  errorText: {
    marginTop: spacing.sm,
    color: colors.coral,
    lineHeight: 20,
    fontWeight: "800",
  },
  submitButton: {
    marginTop: spacing.sm,
    minHeight: 50,
    borderRadius: 999,
    backgroundColor: colors.ink,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 2,
  },
  disabledButton: {
    opacity: 0.7,
  },
  submitButtonText: {
    color: colors.onInk,
    fontWeight: "900",
  },
  briefTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: spacing.sm,
  },
  subsectionTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "900",
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  listText: {
    color: colors.muted,
    lineHeight: 22,
  },
  wrapRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  smallChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: colors.greenSoft,
    color: colors.green,
    fontWeight: "800",
  },
  levelRow: {
    marginTop: spacing.md,
    flexDirection: "row",
    gap: spacing.sm,
  },
  levelChip: {
    flex: 1,
    minHeight: 42,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
  },
  levelChipActive: {
    backgroundColor: colors.lime,
    borderColor: colors.lime,
  },
  levelChipText: {
    color: colors.muted,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  levelChipTextActive: {
    color: colors.limeInk,
  },
  badge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.lavender,
    color: colors.lavenderInk,
    fontWeight: "900",
    overflow: "hidden",
  },
  emptyText: {
    color: colors.muted,
    lineHeight: 22,
  },
  turnCard: {
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.amberSoft,
  },
  agentTurn: {
    backgroundColor: colors.lavender,
    borderColor: colors.lavenderStrong,
  },
  turnRole: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  phaseText: {
    alignSelf: "flex-start",
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: "hidden",
    backgroundColor: colors.surfaceRaised,
    color: colors.lavenderInk,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  turnText: {
    color: colors.ink,
    lineHeight: 22,
  },
  contextBox: {
    marginTop: spacing.sm,
    padding: spacing.sm,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.greenSoft,
    backgroundColor: colors.surfaceRaised,
    gap: spacing.xs,
  },
  contextTitle: {
    color: colors.green,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  contextText: {
    color: colors.muted,
    lineHeight: 20,
  },
  metric: {
    marginTop: spacing.sm,
  },
  metricTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  metricLabel: {
    color: colors.ink,
    fontWeight: "800",
  },
  metricValue: {
    color: colors.muted,
    fontWeight: "800",
  },
  meter: {
    height: 10,
    borderRadius: 999,
    backgroundColor: colors.surfaceMuted,
    overflow: "hidden",
  },
  meterFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: colors.green,
  },
  tipText: {
    marginTop: spacing.md,
    color: colors.muted,
    lineHeight: 22,
  },
  feedbackBox: {
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.lavender,
    backgroundColor: colors.lavender,
    gap: spacing.xs,
  },
  inlineButton: {
    minHeight: 38,
    paddingHorizontal: spacing.md,
    borderRadius: 999,
    backgroundColor: colors.ink,
    justifyContent: "center",
  },
  inlineButtonText: {
    color: colors.onInk,
    fontWeight: "900",
  },
  summaryStack: {
    gap: spacing.sm,
  },
  summaryItem: {
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.line,
    gap: spacing.xs,
  },
  latencyRow: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  latencyLabel: {
    color: colors.ink,
    fontWeight: "800",
  },
  latencyValue: {
    color: colors.muted,
    fontWeight: "800",
  },
});
